AWSTemplateFormatVersion: 2010-09-09
Description: Allow a Lambda from SECU account to act on EC2
Resources:
  Role:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: 
            - "arn:aws:iam::SECU_ID:root" <-- change this
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies: 
        - 
          PolicyName: "DoActionsOnEC2"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeRegions"
                  - "ec2:StartInstances"
                  - "ec2:StopInstances"
                Resource: "*"
      RoleName: 'orga-stopandstartec2-from-secu'